// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewAssignRoleRequestBuilder() AssignRoleRequest_Builder_RoleName {
	return AssignRoleRequest_Builder_RoleName{root: &AssignRoleRequest{}}
}

type AssignRoleRequest_Builder_RoleName struct {
	root *AssignRoleRequest
}

type AssignRoleRequest_Builder_GobFinalizer struct {
	root *AssignRoleRequest
}

func (b AssignRoleRequest_Builder_RoleName) RoleName(arg *string) AssignRoleRequest_Builder_GobFinalizer {
	b.root.RoleName = arg
	return AssignRoleRequest_Builder_GobFinalizer{root: b.root}
}

func (b AssignRoleRequest_Builder_GobFinalizer) Build() *AssignRoleRequest {
	return b.root
}
