// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewEmailConfirmationRequestBuilder() EmailConfirmationRequest_Builder_Code {
	return EmailConfirmationRequest_Builder_Code{root: &EmailConfirmationRequest{}}
}

type EmailConfirmationRequest_Builder_Code struct {
	root *EmailConfirmationRequest
}

type EmailConfirmationRequest_Builder_UserId struct {
	root *EmailConfirmationRequest
}

func (b EmailConfirmationRequest_Builder_Code) Code(arg string) EmailConfirmationRequest_Builder_UserId {
	b.root.Code = arg
	return EmailConfirmationRequest_Builder_UserId{root: b.root}
}

type EmailConfirmationRequest_Builder_GobFinalizer struct {
	root *EmailConfirmationRequest
}

func (b EmailConfirmationRequest_Builder_UserId) UserId(arg string) EmailConfirmationRequest_Builder_GobFinalizer {
	b.root.UserId = arg
	return EmailConfirmationRequest_Builder_GobFinalizer{root: b.root}
}

func (b EmailConfirmationRequest_Builder_GobFinalizer) Build() *EmailConfirmationRequest {
	return b.root
}

func NewEmailConfirmationResponseBuilder() EmailConfirmationResponse_Builder_Message {
	return EmailConfirmationResponse_Builder_Message{root: &EmailConfirmationResponse{}}
}

type EmailConfirmationResponse_Builder_Message struct {
	root *EmailConfirmationResponse
}

type EmailConfirmationResponse_Builder_GobFinalizer struct {
	root *EmailConfirmationResponse
}

func (b EmailConfirmationResponse_Builder_Message) Message(arg string) EmailConfirmationResponse_Builder_GobFinalizer {
	b.root.Message = arg
	return EmailConfirmationResponse_Builder_GobFinalizer{root: b.root}
}

func (b EmailConfirmationResponse_Builder_GobFinalizer) Build() *EmailConfirmationResponse {
	return b.root
}

func NewSignInRequestBuilder() SignInRequest_Builder_Email {
	return SignInRequest_Builder_Email{root: &SignInRequest{}}
}

type SignInRequest_Builder_Email struct {
	root *SignInRequest
}

type SignInRequest_Builder_Password struct {
	root *SignInRequest
}

func (b SignInRequest_Builder_Email) Email(arg string) SignInRequest_Builder_Password {
	b.root.Email = arg
	return SignInRequest_Builder_Password{root: b.root}
}

type SignInRequest_Builder_TenantId struct {
	root *SignInRequest
}

func (b SignInRequest_Builder_Password) Password(arg string) SignInRequest_Builder_TenantId {
	b.root.Password = arg
	return SignInRequest_Builder_TenantId{root: b.root}
}

type SignInRequest_Builder_GobFinalizer struct {
	root *SignInRequest
}

func (b SignInRequest_Builder_TenantId) TenantId(arg string) SignInRequest_Builder_GobFinalizer {
	b.root.TenantId = arg
	return SignInRequest_Builder_GobFinalizer{root: b.root}
}

func (b SignInRequest_Builder_GobFinalizer) Build() *SignInRequest {
	return b.root
}

func NewSignInResponseBuilder() SignInResponse_Builder_AccessToken {
	return SignInResponse_Builder_AccessToken{root: &SignInResponse{}}
}

type SignInResponse_Builder_AccessToken struct {
	root *SignInResponse
}

type SignInResponse_Builder_ExpiresIn struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_AccessToken) AccessToken(arg string) SignInResponse_Builder_ExpiresIn {
	b.root.AccessToken = arg
	return SignInResponse_Builder_ExpiresIn{root: b.root}
}

type SignInResponse_Builder_RefreshToken struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_ExpiresIn) ExpiresIn(arg int64) SignInResponse_Builder_RefreshToken {
	b.root.ExpiresIn = arg
	return SignInResponse_Builder_RefreshToken{root: b.root}
}

type SignInResponse_Builder_TokenType struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_RefreshToken) RefreshToken(arg string) SignInResponse_Builder_TokenType {
	b.root.RefreshToken = arg
	return SignInResponse_Builder_TokenType{root: b.root}
}

type SignInResponse_Builder_UserId struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_TokenType) TokenType(arg string) SignInResponse_Builder_UserId {
	b.root.TokenType = arg
	return SignInResponse_Builder_UserId{root: b.root}
}

type SignInResponse_Builder_GobFinalizer struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_UserId) UserId(arg string) SignInResponse_Builder_GobFinalizer {
	b.root.UserId = arg
	return SignInResponse_Builder_GobFinalizer{root: b.root}
}

func (b SignInResponse_Builder_GobFinalizer) Build() *SignInResponse {
	return b.root
}

func NewSignUpRequestBuilder() SignUpRequest_Builder_Email {
	return SignUpRequest_Builder_Email{root: &SignUpRequest{}}
}

type SignUpRequest_Builder_Email struct {
	root *SignUpRequest
}

type SignUpRequest_Builder_FirstName struct {
	root *SignUpRequest
}

func (b SignUpRequest_Builder_Email) Email(arg string) SignUpRequest_Builder_FirstName {
	b.root.Email = arg
	return SignUpRequest_Builder_FirstName{root: b.root}
}

type SignUpRequest_Builder_LastName struct {
	root *SignUpRequest
}

func (b SignUpRequest_Builder_FirstName) FirstName(arg string) SignUpRequest_Builder_LastName {
	b.root.FirstName = arg
	return SignUpRequest_Builder_LastName{root: b.root}
}

type SignUpRequest_Builder_Password struct {
	root *SignUpRequest
}

func (b SignUpRequest_Builder_LastName) LastName(arg string) SignUpRequest_Builder_Password {
	b.root.LastName = arg
	return SignUpRequest_Builder_Password{root: b.root}
}

type SignUpRequest_Builder_Source struct {
	root *SignUpRequest
}

func (b SignUpRequest_Builder_Password) Password(arg string) SignUpRequest_Builder_Source {
	b.root.Password = arg
	return SignUpRequest_Builder_Source{root: b.root}
}

type SignUpRequest_Builder_TenantId struct {
	root *SignUpRequest
}

func (b SignUpRequest_Builder_Source) Source(arg SignUpRequestSource) SignUpRequest_Builder_TenantId {
	b.root.Source = arg
	return SignUpRequest_Builder_TenantId{root: b.root}
}

type SignUpRequest_Builder_GobFinalizer struct {
	root *SignUpRequest
}

func (b SignUpRequest_Builder_TenantId) TenantId(arg string) SignUpRequest_Builder_GobFinalizer {
	b.root.TenantId = arg
	return SignUpRequest_Builder_GobFinalizer{root: b.root}
}

func (b SignUpRequest_Builder_GobFinalizer) Build() *SignUpRequest {
	return b.root
}

func NewSignUpResponseBuilder() SignUpResponse_Builder_Email {
	return SignUpResponse_Builder_Email{root: &SignUpResponse{}}
}

type SignUpResponse_Builder_Email struct {
	root *SignUpResponse
}

type SignUpResponse_Builder_Message struct {
	root *SignUpResponse
}

func (b SignUpResponse_Builder_Email) Email(arg string) SignUpResponse_Builder_Message {
	b.root.Email = arg
	return SignUpResponse_Builder_Message{root: b.root}
}

type SignUpResponse_Builder_UserId struct {
	root *SignUpResponse
}

func (b SignUpResponse_Builder_Message) Message(arg string) SignUpResponse_Builder_UserId {
	b.root.Message = arg
	return SignUpResponse_Builder_UserId{root: b.root}
}

type SignUpResponse_Builder_GobFinalizer struct {
	root *SignUpResponse
}

func (b SignUpResponse_Builder_UserId) UserId(arg string) SignUpResponse_Builder_GobFinalizer {
	b.root.UserId = arg
	return SignUpResponse_Builder_GobFinalizer{root: b.root}
}

func (b SignUpResponse_Builder_GobFinalizer) Build() *SignUpResponse {
	return b.root
}

func NewTokenRefreshRequestBuilder() TokenRefreshRequest_Builder_RefreshToken {
	return TokenRefreshRequest_Builder_RefreshToken{root: &TokenRefreshRequest{}}
}

type TokenRefreshRequest_Builder_RefreshToken struct {
	root *TokenRefreshRequest
}

type TokenRefreshRequest_Builder_GobFinalizer struct {
	root *TokenRefreshRequest
}

func (b TokenRefreshRequest_Builder_RefreshToken) RefreshToken(arg string) TokenRefreshRequest_Builder_GobFinalizer {
	b.root.RefreshToken = arg
	return TokenRefreshRequest_Builder_GobFinalizer{root: b.root}
}

func (b TokenRefreshRequest_Builder_GobFinalizer) Build() *TokenRefreshRequest {
	return b.root
}
