// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewEmailConfirmationResponseBuilder() EmailConfirmationResponse_Builder_Message {
	return EmailConfirmationResponse_Builder_Message{root: &EmailConfirmationResponse{}}
}

type EmailConfirmationResponse_Builder_Message struct {
	root *EmailConfirmationResponse
}

type EmailConfirmationResponse_Builder_GobFinalizer struct {
	root *EmailConfirmationResponse
}

func (b EmailConfirmationResponse_Builder_Message) Message(arg string) EmailConfirmationResponse_Builder_GobFinalizer {
	b.root.Message = arg
	return EmailConfirmationResponse_Builder_GobFinalizer{root: b.root}
}

func (b EmailConfirmationResponse_Builder_GobFinalizer) Build() *EmailConfirmationResponse {
	return b.root
}

func NewRefreshRequestBuilder() RefreshRequest_Builder_RefreshToken {
	return RefreshRequest_Builder_RefreshToken{root: &RefreshRequest{}}
}

type RefreshRequest_Builder_RefreshToken struct {
	root *RefreshRequest
}

type RefreshRequest_Builder_GobFinalizer struct {
	root *RefreshRequest
}

func (b RefreshRequest_Builder_RefreshToken) RefreshToken(arg string) RefreshRequest_Builder_GobFinalizer {
	b.root.RefreshToken = arg
	return RefreshRequest_Builder_GobFinalizer{root: b.root}
}

func (b RefreshRequest_Builder_GobFinalizer) Build() *RefreshRequest {
	return b.root
}

func NewSignInRequestBuilder() SignInRequest_Builder_Email {
	return SignInRequest_Builder_Email{root: &SignInRequest{}}
}

type SignInRequest_Builder_Email struct {
	root *SignInRequest
}

type SignInRequest_Builder_Password struct {
	root *SignInRequest
}

func (b SignInRequest_Builder_Email) Email(arg string) SignInRequest_Builder_Password {
	b.root.Email = arg
	return SignInRequest_Builder_Password{root: b.root}
}

type SignInRequest_Builder_TenantId struct {
	root *SignInRequest
}

func (b SignInRequest_Builder_Password) Password(arg string) SignInRequest_Builder_TenantId {
	b.root.Password = arg
	return SignInRequest_Builder_TenantId{root: b.root}
}

type SignInRequest_Builder_GobFinalizer struct {
	root *SignInRequest
}

func (b SignInRequest_Builder_TenantId) TenantId(arg string) SignInRequest_Builder_GobFinalizer {
	b.root.TenantId = arg
	return SignInRequest_Builder_GobFinalizer{root: b.root}
}

func (b SignInRequest_Builder_GobFinalizer) Build() *SignInRequest {
	return b.root
}

func NewSignInResponseBuilder() SignInResponse_Builder_AccessToken {
	return SignInResponse_Builder_AccessToken{root: &SignInResponse{}}
}

type SignInResponse_Builder_AccessToken struct {
	root *SignInResponse
}

type SignInResponse_Builder_ExpiresIn struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_AccessToken) AccessToken(arg string) SignInResponse_Builder_ExpiresIn {
	b.root.AccessToken = arg
	return SignInResponse_Builder_ExpiresIn{root: b.root}
}

type SignInResponse_Builder_RefreshToken struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_ExpiresIn) ExpiresIn(arg int64) SignInResponse_Builder_RefreshToken {
	b.root.ExpiresIn = arg
	return SignInResponse_Builder_RefreshToken{root: b.root}
}

type SignInResponse_Builder_TokenType struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_RefreshToken) RefreshToken(arg string) SignInResponse_Builder_TokenType {
	b.root.RefreshToken = arg
	return SignInResponse_Builder_TokenType{root: b.root}
}

type SignInResponse_Builder_UserId struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_TokenType) TokenType(arg string) SignInResponse_Builder_UserId {
	b.root.TokenType = arg
	return SignInResponse_Builder_UserId{root: b.root}
}

type SignInResponse_Builder_GobFinalizer struct {
	root *SignInResponse
}

func (b SignInResponse_Builder_UserId) UserId(arg string) SignInResponse_Builder_GobFinalizer {
	b.root.UserId = arg
	return SignInResponse_Builder_GobFinalizer{root: b.root}
}

func (b SignInResponse_Builder_GobFinalizer) Build() *SignInResponse {
	return b.root
}

func NewSignupRequestBuilder() SignupRequest_Builder_Email {
	return SignupRequest_Builder_Email{root: &SignupRequest{}}
}

type SignupRequest_Builder_Email struct {
	root *SignupRequest
}

type SignupRequest_Builder_FirstName struct {
	root *SignupRequest
}

func (b SignupRequest_Builder_Email) Email(arg string) SignupRequest_Builder_FirstName {
	b.root.Email = arg
	return SignupRequest_Builder_FirstName{root: b.root}
}

type SignupRequest_Builder_LastName struct {
	root *SignupRequest
}

func (b SignupRequest_Builder_FirstName) FirstName(arg string) SignupRequest_Builder_LastName {
	b.root.FirstName = arg
	return SignupRequest_Builder_LastName{root: b.root}
}

type SignupRequest_Builder_Password struct {
	root *SignupRequest
}

func (b SignupRequest_Builder_LastName) LastName(arg string) SignupRequest_Builder_Password {
	b.root.LastName = arg
	return SignupRequest_Builder_Password{root: b.root}
}

type SignupRequest_Builder_Source struct {
	root *SignupRequest
}

func (b SignupRequest_Builder_Password) Password(arg string) SignupRequest_Builder_Source {
	b.root.Password = arg
	return SignupRequest_Builder_Source{root: b.root}
}

type SignupRequest_Builder_TenantId struct {
	root *SignupRequest
}

func (b SignupRequest_Builder_Source) Source(arg SignupRequestSource) SignupRequest_Builder_TenantId {
	b.root.Source = arg
	return SignupRequest_Builder_TenantId{root: b.root}
}

type SignupRequest_Builder_GobFinalizer struct {
	root *SignupRequest
}

func (b SignupRequest_Builder_TenantId) TenantId(arg string) SignupRequest_Builder_GobFinalizer {
	b.root.TenantId = arg
	return SignupRequest_Builder_GobFinalizer{root: b.root}
}

func (b SignupRequest_Builder_GobFinalizer) Build() *SignupRequest {
	return b.root
}

func NewSignupResponseBuilder() SignupResponse_Builder_Email {
	return SignupResponse_Builder_Email{root: &SignupResponse{}}
}

type SignupResponse_Builder_Email struct {
	root *SignupResponse
}

type SignupResponse_Builder_Message struct {
	root *SignupResponse
}

func (b SignupResponse_Builder_Email) Email(arg string) SignupResponse_Builder_Message {
	b.root.Email = arg
	return SignupResponse_Builder_Message{root: b.root}
}

type SignupResponse_Builder_UserId struct {
	root *SignupResponse
}

func (b SignupResponse_Builder_Message) Message(arg string) SignupResponse_Builder_UserId {
	b.root.Message = arg
	return SignupResponse_Builder_UserId{root: b.root}
}

type SignupResponse_Builder_GobFinalizer struct {
	root *SignupResponse
}

func (b SignupResponse_Builder_UserId) UserId(arg string) SignupResponse_Builder_GobFinalizer {
	b.root.UserId = arg
	return SignupResponse_Builder_GobFinalizer{root: b.root}
}

func (b SignupResponse_Builder_GobFinalizer) Build() *SignupResponse {
	return b.root
}

func NewConfirmEmailParamsBuilder() ConfirmEmailParams_Builder_UserId {
	return ConfirmEmailParams_Builder_UserId{root: &ConfirmEmailParams{}}
}

type ConfirmEmailParams_Builder_UserId struct {
	root *ConfirmEmailParams
}

type ConfirmEmailParams_Builder_Code struct {
	root *ConfirmEmailParams
}

func (b ConfirmEmailParams_Builder_UserId) UserId(arg string) ConfirmEmailParams_Builder_Code {
	b.root.UserId = arg
	return ConfirmEmailParams_Builder_Code{root: b.root}
}

type ConfirmEmailParams_Builder_GobFinalizer struct {
	root *ConfirmEmailParams
}

func (b ConfirmEmailParams_Builder_Code) Code(arg string) ConfirmEmailParams_Builder_GobFinalizer {
	b.root.Code = arg
	return ConfirmEmailParams_Builder_GobFinalizer{root: b.root}
}

func (b ConfirmEmailParams_Builder_GobFinalizer) Build() *ConfirmEmailParams {
	return b.root
}
