// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewAuthResponseBuilder() AuthResponse_Builder_AccessToken {
	return AuthResponse_Builder_AccessToken{root: &AuthResponse{}}
}

type AuthResponse_Builder_AccessToken struct {
	root *AuthResponse
}

type AuthResponse_Builder_RefreshToken struct {
	root *AuthResponse
}

func (b AuthResponse_Builder_AccessToken) AccessToken(arg *string) AuthResponse_Builder_RefreshToken {
	b.root.AccessToken = arg
	return AuthResponse_Builder_RefreshToken{root: b.root}
}

type AuthResponse_Builder_TokenType struct {
	root *AuthResponse
}

func (b AuthResponse_Builder_RefreshToken) RefreshToken(arg *string) AuthResponse_Builder_TokenType {
	b.root.RefreshToken = arg
	return AuthResponse_Builder_TokenType{root: b.root}
}

type AuthResponse_Builder_ExpiresIn struct {
	root *AuthResponse
}

func (b AuthResponse_Builder_TokenType) TokenType(arg *string) AuthResponse_Builder_ExpiresIn {
	b.root.TokenType = arg
	return AuthResponse_Builder_ExpiresIn{root: b.root}
}

type AuthResponse_Builder_GobFinalizer struct {
	root *AuthResponse
}

func (b AuthResponse_Builder_ExpiresIn) ExpiresIn(arg *int64) AuthResponse_Builder_GobFinalizer {
	b.root.ExpiresIn = arg
	return AuthResponse_Builder_GobFinalizer{root: b.root}
}

func (b AuthResponse_Builder_GobFinalizer) Build() *AuthResponse {
	return b.root
}
