// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewMessageResponseBuilder() MessageResponse_Builder_Message {
	return MessageResponse_Builder_Message{root: &MessageResponse{}}
}

type MessageResponse_Builder_Message struct {
	root *MessageResponse
}

type MessageResponse_Builder_GobFinalizer struct {
	root *MessageResponse
}

func (b MessageResponse_Builder_Message) Message(arg *string) MessageResponse_Builder_GobFinalizer {
	b.root.Message = arg
	return MessageResponse_Builder_GobFinalizer{root: b.root}
}

func (b MessageResponse_Builder_GobFinalizer) Build() *MessageResponse {
	return b.root
}
