// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewPaginationInfoBuilder() PaginationInfo_Builder_Page {
	return PaginationInfo_Builder_Page{root: &PaginationInfo{}}
}

type PaginationInfo_Builder_Page struct {
	root *PaginationInfo
}

type PaginationInfo_Builder_Limit struct {
	root *PaginationInfo
}

func (b PaginationInfo_Builder_Page) Page(arg *int64) PaginationInfo_Builder_Limit {
	b.root.Page = arg
	return PaginationInfo_Builder_Limit{root: b.root}
}

type PaginationInfo_Builder_Total struct {
	root *PaginationInfo
}

func (b PaginationInfo_Builder_Limit) Limit(arg *int64) PaginationInfo_Builder_Total {
	b.root.Limit = arg
	return PaginationInfo_Builder_Total{root: b.root}
}

type PaginationInfo_Builder_TotalPages struct {
	root *PaginationInfo
}

func (b PaginationInfo_Builder_Total) Total(arg *int64) PaginationInfo_Builder_TotalPages {
	b.root.Total = arg
	return PaginationInfo_Builder_TotalPages{root: b.root}
}

type PaginationInfo_Builder_GobFinalizer struct {
	root *PaginationInfo
}

func (b PaginationInfo_Builder_TotalPages) TotalPages(arg *int64) PaginationInfo_Builder_GobFinalizer {
	b.root.TotalPages = arg
	return PaginationInfo_Builder_GobFinalizer{root: b.root}
}

func (b PaginationInfo_Builder_GobFinalizer) Build() *PaginationInfo {
	return b.root
}
