// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewRefreshRequestBuilder() RefreshRequest_Builder_RefreshToken {
	return RefreshRequest_Builder_RefreshToken{root: &RefreshRequest{}}
}

type RefreshRequest_Builder_RefreshToken struct {
	root *RefreshRequest
}

type RefreshRequest_Builder_GobFinalizer struct {
	root *RefreshRequest
}

func (b RefreshRequest_Builder_RefreshToken) RefreshToken(arg string) RefreshRequest_Builder_GobFinalizer {
	b.root.RefreshToken = arg
	return RefreshRequest_Builder_GobFinalizer{root: b.root}
}

func (b RefreshRequest_Builder_GobFinalizer) Build() *RefreshRequest {
	return b.root
}
