// Code generated by gobetter; DO NOT EDIT.

package swagger

import (
	"github.com/go-openapi/strfmt"
)

func NewSigninRequestBuilder() SigninRequest_Builder_Email {
	return SigninRequest_Builder_Email{root: &SigninRequest{}}
}

type SigninRequest_Builder_Email struct {
	root *SigninRequest
}

type SigninRequest_Builder_Password struct {
	root *SigninRequest
}

func (b SigninRequest_Builder_Email) Email(arg *strfmt.Email) SigninRequest_Builder_Password {
	b.root.Email = arg
	return SigninRequest_Builder_Password{root: b.root}
}

type SigninRequest_Builder_GobFinalizer struct {
	root *SigninRequest
}

func (b SigninRequest_Builder_Password) Password(arg *string) SigninRequest_Builder_GobFinalizer {
	b.root.Password = arg
	return SigninRequest_Builder_GobFinalizer{root: b.root}
}

func (b SigninRequest_Builder_GobFinalizer) Build() *SigninRequest {
	return b.root
}
