// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SignupResponse Response after successful user signup indicating email confirmation is required
//
// swagger:model SignupResponse
type SignupResponse struct {

	// Email address where confirmation was sent
	// Required: true
	// Format: email
	Email strfmt.Email `json:"email"`

	// Success message
	// Example: User account created successfully. Please check your email to confirm your account.
	// Required: true
	Message string `json:"message"`

	// ID of the created user
	// Required: true
	UserID string `json:"userId"`
}

// Validate validates this signup response
func (m *SignupResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SignupResponse) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", strfmt.Email(m.Email)); err != nil {
		return err
	}

	if err := validate.FormatOf("email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SignupResponse) validateMessage(formats strfmt.Registry) error {

	if err := validate.RequiredString("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *SignupResponse) validateUserID(formats strfmt.Registry) error {

	if err := validate.RequiredString("userId", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this signup response based on context it is used
func (m *SignupResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignupResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignupResponse) UnmarshalBinary(b []byte) error {
	var res SignupResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
