// Code generated by gobetter; DO NOT EDIT.

package swagger

import (
	"github.com/go-openapi/strfmt"
)

func NewSignupResponseBuilder() SignupResponse_Builder_Email {
	return SignupResponse_Builder_Email{root: &SignupResponse{}}
}

type SignupResponse_Builder_Email struct {
	root *SignupResponse
}

type SignupResponse_Builder_Message struct {
	root *SignupResponse
}

func (b SignupResponse_Builder_Email) Email(arg strfmt.Email) SignupResponse_Builder_Message {
	b.root.Email = arg
	return SignupResponse_Builder_Message{root: b.root}
}

type SignupResponse_Builder_UserID struct {
	root *SignupResponse
}

func (b SignupResponse_Builder_Message) Message(arg string) SignupResponse_Builder_UserID {
	b.root.Message = arg
	return SignupResponse_Builder_UserID{root: b.root}
}

type SignupResponse_Builder_GobFinalizer struct {
	root *SignupResponse
}

func (b SignupResponse_Builder_UserID) UserID(arg string) SignupResponse_Builder_GobFinalizer {
	b.root.UserID = arg
	return SignupResponse_Builder_GobFinalizer{root: b.root}
}

func (b SignupResponse_Builder_GobFinalizer) Build() *SignupResponse {
	return b.root
}
