// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package swagger

import (
	"time"
)

// TenantCreateRequest Request payload for creating a new tenant
type TenantCreateRequest struct {
	// Description Optional description of the tenant
	Description string `json:"description"`

	// Id Unique tenant identifier
	Id string `json:"id"`

	// Name Human-readable tenant name
	Name string `json:"name"`
}

// TenantListResponse defines model for TenantListResponse.
type TenantListResponse struct {
	Pagination PaginationInfo   `json:"pagination"`
	Tenants    []TenantResponse `json:"tenants"`
}

// TenantResponse Tenant information response
type TenantResponse struct {
	// CreatedAt Tenant creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the tenant
	Description string `json:"description"`

	// Id Unique tenant identifier
	Id string `json:"id"`

	// Name Human-readable tenant name
	Name string `json:"name"`

	// UpdatedAt Last tenant update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// TenantUpdateRequest Request payload for updating a tenant
type TenantUpdateRequest struct {
	// Description Optional description of the tenant
	Description string `json:"description"`

	// Name Human-readable tenant name
	Name string `json:"name"`
}

// GetAllTenantsParams defines parameters for GetAllTenants.
type GetAllTenantsParams struct {
	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of tenants per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Active Filter by active status
	Active *bool `form:"active,omitempty" json:"active,omitempty"`
}

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = TenantCreateRequest

// UpdateTenantByIdJSONRequestBody defines body for UpdateTenantById for application/json ContentType.
type UpdateTenantByIdJSONRequestBody = TenantUpdateRequest
