// Code generated by gobetter; DO NOT EDIT.

package swagger

import (
	"github.com/go-openapi/strfmt"
)

func NewTenantResponseBuilder() TenantResponse_Builder_CreatedAt {
	return TenantResponse_Builder_CreatedAt{root: &TenantResponse{}}
}

type TenantResponse_Builder_CreatedAt struct {
	root *TenantResponse
}

type TenantResponse_Builder_Description struct {
	root *TenantResponse
}

func (b TenantResponse_Builder_CreatedAt) CreatedAt(arg strfmt.DateTime) TenantResponse_Builder_Description {
	b.root.CreatedAt = arg
	return TenantResponse_Builder_Description{root: b.root}
}

type TenantResponse_Builder_ID struct {
	root *TenantResponse
}

func (b TenantResponse_Builder_Description) Description(arg string) TenantResponse_Builder_ID {
	b.root.Description = arg
	return TenantResponse_Builder_ID{root: b.root}
}

type TenantResponse_Builder_Name struct {
	root *TenantResponse
}

func (b TenantResponse_Builder_ID) ID(arg string) TenantResponse_Builder_Name {
	b.root.ID = arg
	return TenantResponse_Builder_Name{root: b.root}
}

type TenantResponse_Builder_UpdatedAt struct {
	root *TenantResponse
}

func (b TenantResponse_Builder_Name) Name(arg string) TenantResponse_Builder_UpdatedAt {
	b.root.Name = arg
	return TenantResponse_Builder_UpdatedAt{root: b.root}
}

type TenantResponse_Builder_GobFinalizer struct {
	root *TenantResponse
}

func (b TenantResponse_Builder_UpdatedAt) UpdatedAt(arg strfmt.DateTime) TenantResponse_Builder_GobFinalizer {
	b.root.UpdatedAt = arg
	return TenantResponse_Builder_GobFinalizer{root: b.root}
}

func (b TenantResponse_Builder_GobFinalizer) Build() *TenantResponse {
	return b.root
}
