// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewTenantCreateRequestBuilder() TenantCreateRequest_Builder_Description {
	return TenantCreateRequest_Builder_Description{root: &TenantCreateRequest{}}
}

type TenantCreateRequest_Builder_Description struct {
	root *TenantCreateRequest
}

type TenantCreateRequest_Builder_ID struct {
	root *TenantCreateRequest
}

func (b TenantCreateRequest_Builder_Description) Description(arg string) TenantCreateRequest_Builder_ID {
	b.root.Description = arg
	return TenantCreateRequest_Builder_ID{root: b.root}
}

type TenantCreateRequest_Builder_Name struct {
	root *TenantCreateRequest
}

func (b TenantCreateRequest_Builder_ID) ID(arg string) TenantCreateRequest_Builder_Name {
	b.root.ID = arg
	return TenantCreateRequest_Builder_Name{root: b.root}
}

type TenantCreateRequest_Builder_GobFinalizer struct {
	root *TenantCreateRequest
}

func (b TenantCreateRequest_Builder_Name) Name(arg string) TenantCreateRequest_Builder_GobFinalizer {
	b.root.Name = arg
	return TenantCreateRequest_Builder_GobFinalizer{root: b.root}
}

func (b TenantCreateRequest_Builder_GobFinalizer) Build() *TenantCreateRequest {
	return b.root
}
