// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewTenantUpdateRequestBuilder() TenantUpdateRequest_Builder_Description {
	return TenantUpdateRequest_Builder_Description{root: &TenantUpdateRequest{}}
}

type TenantUpdateRequest_Builder_Description struct {
	root *TenantUpdateRequest
}

type TenantUpdateRequest_Builder_Name struct {
	root *TenantUpdateRequest
}

func (b TenantUpdateRequest_Builder_Description) Description(arg string) TenantUpdateRequest_Builder_Name {
	b.root.Description = arg
	return TenantUpdateRequest_Builder_Name{root: b.root}
}

type TenantUpdateRequest_Builder_GobFinalizer struct {
	root *TenantUpdateRequest
}

func (b TenantUpdateRequest_Builder_Name) Name(arg string) TenantUpdateRequest_Builder_GobFinalizer {
	b.root.Name = arg
	return TenantUpdateRequest_Builder_GobFinalizer{root: b.root}
}

func (b TenantUpdateRequest_Builder_GobFinalizer) Build() *TenantUpdateRequest {
	return b.root
}
