// Code generated by gobetter; DO NOT EDIT.

package swagger

func NewTenantListResponseBuilder() TenantListResponse_Builder_Pagination {
	return TenantListResponse_Builder_Pagination{root: &TenantListResponse{}}
}

type TenantListResponse_Builder_Pagination struct {
	root *TenantListResponse
}

type TenantListResponse_Builder_Tenants struct {
	root *TenantListResponse
}

func (b TenantListResponse_Builder_Pagination) Pagination(arg *PaginationInfo) TenantListResponse_Builder_Tenants {
	b.root.Pagination = arg
	return TenantListResponse_Builder_Tenants{root: b.root}
}

type TenantListResponse_Builder_GobFinalizer struct {
	root *TenantListResponse
}

func (b TenantListResponse_Builder_Tenants) Tenants(arg []*TenantResponse) TenantListResponse_Builder_GobFinalizer {
	b.root.Tenants = arg
	return TenantListResponse_Builder_GobFinalizer{root: b.root}
}

func (b TenantListResponse_Builder_GobFinalizer) Build() *TenantListResponse {
	return b.root
}
