// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TenantCreateRequest Request payload for creating a new tenant
//
// swagger:model TenantCreateRequest
type TenantCreateRequest struct {

	// Optional description of the tenant
	// Example: Acme Corporation tenant for enterprise customers
	// Required: true
	Description string `json:"description"`

	// Unique tenant identifier
	// Example: acme-corp
	// Required: true
	ID string `json:"id"`

	// Human-readable tenant name
	// Example: Acme Corporation
	// Required: true
	Name string `json:"name"`
}

// Validate validates this tenant create request
func (m *TenantCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TenantCreateRequest) validateDescription(formats strfmt.Registry) error {

	if err := validate.RequiredString("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *TenantCreateRequest) validateID(formats strfmt.Registry) error {

	if err := validate.RequiredString("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *TenantCreateRequest) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this tenant create request based on context it is used
func (m *TenantCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TenantCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TenantCreateRequest) UnmarshalBinary(b []byte) error {
	var res TenantCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
