// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package swagger

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AssignRoleRequestRoleName.
const (
	Admin     AssignRoleRequestRoleName = "admin"
	Moderator AssignRoleRequestRoleName = "moderator"
	User      AssignRoleRequestRoleName = "user"
)

// Defines values for UserProfileGender.
const (
	Female UserProfileGender = "female"
	Male   UserProfileGender = "male"
	Other  UserProfileGender = "other"
)

// AssignRoleRequest defines model for AssignRoleRequest.
type AssignRoleRequest struct {
	// RoleName Name of the role to assign
	RoleName AssignRoleRequestRoleName `json:"roleName"`
}

// AssignRoleRequestRoleName Name of the role to assign
type AssignRoleRequestRoleName string

// AuthUserResponse Authentication user data from auth_user table (excluding sensitive fields)
type AuthUserResponse struct {
	// CreatedAt Account creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Email User email address (unique in auth_user table)
	Email openapi_types.Email `json:"email"`

	// FirstName User first name
	FirstName string `json:"firstName"`

	// Id User unique identifier (primary key from auth_user table)
	Id string `json:"id"`

	// LastName User last name
	LastName string `json:"lastName"`

	// TenantId Tenant identifier for multi-tenant support
	TenantId string `json:"tenantId"`

	// UpdatedAt Last profile update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Pagination PaginationInfo     `json:"pagination"`
	Users      []AuthUserResponse `json:"users"`
}

// UserProfile User profile data from user_profile table
type UserProfile struct {
	// BirthDate User birth date
	BirthDate *openapi_types.Date `json:"birthDate"`

	// CreatedAt Profile creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// Gender User gender (male/female/other)
	Gender *UserProfileGender `json:"gender"`

	// Height User height in centimeters
	Height *int `json:"height"`

	// Id Profile unique identifier (primary key from user_profile table)
	Id int `json:"id"`

	// IsMetric Whether to use metric units (true) or imperial units (false)
	IsMetric bool `json:"isMetric"`

	// UpdatedAt Last profile update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// UserId User unique identifier (foreign key to auth_user table)
	UserId string `json:"userId"`

	// Weight User weight in grams
	Weight *int `json:"weight"`
}

// UserProfileGender User gender (male/female/other)
type UserProfileGender string

// UserProfileUpdateRequest User profile update request data
type UserProfileUpdateRequest struct {
	// BirthDate User birth date in YYYY-MM-DD format
	BirthDate *openapi_types.Date `json:"birthDate"`

	// Gender User gender
	Gender *string `json:"gender"`

	// Height User height in centimeters
	Height *int `json:"height"`

	// IsMetric Whether to use metric units (true) or imperial units (false)
	IsMetric *bool `json:"isMetric"`

	// Weight User weight in grams
	Weight *int `json:"weight"`
}

// UserRolesResponse defines model for UserRolesResponse.
type UserRolesResponse struct {
	// Roles List of role names assigned to the user
	Roles  []string `json:"roles"`
	UserId string   `json:"userId"`
}

// ListAllUsersParams defines parameters for ListAllUsers.
type ListAllUsersParams struct {
	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of users per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListUsersByTenantParams defines parameters for ListUsersByTenant.
type ListUsersByTenantParams struct {
	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of users per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateUserProfileJSONRequestBody defines body for UpdateUserProfile for application/json ContentType.
type UpdateUserProfileJSONRequestBody = UserProfileUpdateRequest

// AssignUserRoleJSONRequestBody defines body for AssignUserRole for application/json ContentType.
type AssignUserRoleJSONRequestBody = AssignRoleRequest
