// Code generated by gobetter; DO NOT EDIT.

package swagger

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

func NewAssignRoleRequestBuilder() AssignRoleRequest_Builder_RoleName {
	return AssignRoleRequest_Builder_RoleName{root: &AssignRoleRequest{}}
}

type AssignRoleRequest_Builder_RoleName struct {
	root *AssignRoleRequest
}

type AssignRoleRequest_Builder_GobFinalizer struct {
	root *AssignRoleRequest
}

func (b AssignRoleRequest_Builder_RoleName) RoleName(arg AssignRoleRequestRoleName) AssignRoleRequest_Builder_GobFinalizer {
	b.root.RoleName = arg
	return AssignRoleRequest_Builder_GobFinalizer{root: b.root}
}

func (b AssignRoleRequest_Builder_GobFinalizer) Build() *AssignRoleRequest {
	return b.root
}

func NewAuthUserResponseBuilder() AuthUserResponse_Builder_CreatedAt {
	return AuthUserResponse_Builder_CreatedAt{root: &AuthUserResponse{}}
}

type AuthUserResponse_Builder_CreatedAt struct {
	root *AuthUserResponse
}

type AuthUserResponse_Builder_Email struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_CreatedAt) CreatedAt(arg time.Time) AuthUserResponse_Builder_Email {
	b.root.CreatedAt = arg
	return AuthUserResponse_Builder_Email{root: b.root}
}

type AuthUserResponse_Builder_FirstName struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_Email) Email(arg openapi_types.Email) AuthUserResponse_Builder_FirstName {
	b.root.Email = arg
	return AuthUserResponse_Builder_FirstName{root: b.root}
}

type AuthUserResponse_Builder_Id struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_FirstName) FirstName(arg string) AuthUserResponse_Builder_Id {
	b.root.FirstName = arg
	return AuthUserResponse_Builder_Id{root: b.root}
}

type AuthUserResponse_Builder_LastName struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_Id) Id(arg string) AuthUserResponse_Builder_LastName {
	b.root.Id = arg
	return AuthUserResponse_Builder_LastName{root: b.root}
}

type AuthUserResponse_Builder_TenantId struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_LastName) LastName(arg string) AuthUserResponse_Builder_TenantId {
	b.root.LastName = arg
	return AuthUserResponse_Builder_TenantId{root: b.root}
}

type AuthUserResponse_Builder_UpdatedAt struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_TenantId) TenantId(arg string) AuthUserResponse_Builder_UpdatedAt {
	b.root.TenantId = arg
	return AuthUserResponse_Builder_UpdatedAt{root: b.root}
}

type AuthUserResponse_Builder_GobFinalizer struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_UpdatedAt) UpdatedAt(arg time.Time) AuthUserResponse_Builder_GobFinalizer {
	b.root.UpdatedAt = arg
	return AuthUserResponse_Builder_GobFinalizer{root: b.root}
}

func (b AuthUserResponse_Builder_GobFinalizer) Build() *AuthUserResponse {
	return b.root
}

func NewUserListResponseBuilder() UserListResponse_Builder_Pagination {
	return UserListResponse_Builder_Pagination{root: &UserListResponse{}}
}

type UserListResponse_Builder_Pagination struct {
	root *UserListResponse
}

type UserListResponse_Builder_Users struct {
	root *UserListResponse
}

func (b UserListResponse_Builder_Pagination) Pagination(arg PaginationInfo) UserListResponse_Builder_Users {
	b.root.Pagination = arg
	return UserListResponse_Builder_Users{root: b.root}
}

type UserListResponse_Builder_GobFinalizer struct {
	root *UserListResponse
}

func (b UserListResponse_Builder_Users) Users(arg []AuthUserResponse) UserListResponse_Builder_GobFinalizer {
	b.root.Users = arg
	return UserListResponse_Builder_GobFinalizer{root: b.root}
}

func (b UserListResponse_Builder_GobFinalizer) Build() *UserListResponse {
	return b.root
}

func NewUserProfileBuilder() UserProfile_Builder_BirthDate {
	return UserProfile_Builder_BirthDate{root: &UserProfile{}}
}

type UserProfile_Builder_BirthDate struct {
	root *UserProfile
}

type UserProfile_Builder_CreatedAt struct {
	root *UserProfile
}

func (b UserProfile_Builder_BirthDate) BirthDate(arg *openapi_types.Date) UserProfile_Builder_CreatedAt {
	b.root.BirthDate = arg
	return UserProfile_Builder_CreatedAt{root: b.root}
}

type UserProfile_Builder_Gender struct {
	root *UserProfile
}

func (b UserProfile_Builder_CreatedAt) CreatedAt(arg time.Time) UserProfile_Builder_Gender {
	b.root.CreatedAt = arg
	return UserProfile_Builder_Gender{root: b.root}
}

type UserProfile_Builder_Height struct {
	root *UserProfile
}

func (b UserProfile_Builder_Gender) Gender(arg *UserProfileGender) UserProfile_Builder_Height {
	b.root.Gender = arg
	return UserProfile_Builder_Height{root: b.root}
}

type UserProfile_Builder_Id struct {
	root *UserProfile
}

func (b UserProfile_Builder_Height) Height(arg *int) UserProfile_Builder_Id {
	b.root.Height = arg
	return UserProfile_Builder_Id{root: b.root}
}

type UserProfile_Builder_IsMetric struct {
	root *UserProfile
}

func (b UserProfile_Builder_Id) Id(arg int) UserProfile_Builder_IsMetric {
	b.root.Id = arg
	return UserProfile_Builder_IsMetric{root: b.root}
}

type UserProfile_Builder_UpdatedAt struct {
	root *UserProfile
}

func (b UserProfile_Builder_IsMetric) IsMetric(arg bool) UserProfile_Builder_UpdatedAt {
	b.root.IsMetric = arg
	return UserProfile_Builder_UpdatedAt{root: b.root}
}

type UserProfile_Builder_UserId struct {
	root *UserProfile
}

func (b UserProfile_Builder_UpdatedAt) UpdatedAt(arg time.Time) UserProfile_Builder_UserId {
	b.root.UpdatedAt = arg
	return UserProfile_Builder_UserId{root: b.root}
}

type UserProfile_Builder_Weight struct {
	root *UserProfile
}

func (b UserProfile_Builder_UserId) UserId(arg string) UserProfile_Builder_Weight {
	b.root.UserId = arg
	return UserProfile_Builder_Weight{root: b.root}
}

type UserProfile_Builder_GobFinalizer struct {
	root *UserProfile
}

func (b UserProfile_Builder_Weight) Weight(arg *int) UserProfile_Builder_GobFinalizer {
	b.root.Weight = arg
	return UserProfile_Builder_GobFinalizer{root: b.root}
}

func (b UserProfile_Builder_GobFinalizer) Build() *UserProfile {
	return b.root
}

func NewUserProfileUpdateRequestBuilder() UserProfileUpdateRequest_Builder_BirthDate {
	return UserProfileUpdateRequest_Builder_BirthDate{root: &UserProfileUpdateRequest{}}
}

type UserProfileUpdateRequest_Builder_BirthDate struct {
	root *UserProfileUpdateRequest
}

type UserProfileUpdateRequest_Builder_Gender struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_BirthDate) BirthDate(arg *openapi_types.Date) UserProfileUpdateRequest_Builder_Gender {
	b.root.BirthDate = arg
	return UserProfileUpdateRequest_Builder_Gender{root: b.root}
}

type UserProfileUpdateRequest_Builder_Height struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_Gender) Gender(arg *string) UserProfileUpdateRequest_Builder_Height {
	b.root.Gender = arg
	return UserProfileUpdateRequest_Builder_Height{root: b.root}
}

type UserProfileUpdateRequest_Builder_IsMetric struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_Height) Height(arg *int) UserProfileUpdateRequest_Builder_IsMetric {
	b.root.Height = arg
	return UserProfileUpdateRequest_Builder_IsMetric{root: b.root}
}

type UserProfileUpdateRequest_Builder_Weight struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_IsMetric) IsMetric(arg *bool) UserProfileUpdateRequest_Builder_Weight {
	b.root.IsMetric = arg
	return UserProfileUpdateRequest_Builder_Weight{root: b.root}
}

type UserProfileUpdateRequest_Builder_GobFinalizer struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_Weight) Weight(arg *int) UserProfileUpdateRequest_Builder_GobFinalizer {
	b.root.Weight = arg
	return UserProfileUpdateRequest_Builder_GobFinalizer{root: b.root}
}

func (b UserProfileUpdateRequest_Builder_GobFinalizer) Build() *UserProfileUpdateRequest {
	return b.root
}

func NewUserRolesResponseBuilder() UserRolesResponse_Builder_Roles {
	return UserRolesResponse_Builder_Roles{root: &UserRolesResponse{}}
}

type UserRolesResponse_Builder_Roles struct {
	root *UserRolesResponse
}

type UserRolesResponse_Builder_UserId struct {
	root *UserRolesResponse
}

func (b UserRolesResponse_Builder_Roles) Roles(arg []string) UserRolesResponse_Builder_UserId {
	b.root.Roles = arg
	return UserRolesResponse_Builder_UserId{root: b.root}
}

type UserRolesResponse_Builder_GobFinalizer struct {
	root *UserRolesResponse
}

func (b UserRolesResponse_Builder_UserId) UserId(arg string) UserRolesResponse_Builder_GobFinalizer {
	b.root.UserId = arg
	return UserRolesResponse_Builder_GobFinalizer{root: b.root}
}

func (b UserRolesResponse_Builder_GobFinalizer) Build() *UserRolesResponse {
	return b.root
}

func NewListAllUsersParamsBuilder() ListAllUsersParams_Builder_Page {
	return ListAllUsersParams_Builder_Page{root: &ListAllUsersParams{}}
}

type ListAllUsersParams_Builder_Page struct {
	root *ListAllUsersParams
}

type ListAllUsersParams_Builder_Limit struct {
	root *ListAllUsersParams
}

func (b ListAllUsersParams_Builder_Page) Page(arg *int) ListAllUsersParams_Builder_Limit {
	b.root.Page = arg
	return ListAllUsersParams_Builder_Limit{root: b.root}
}

type ListAllUsersParams_Builder_GobFinalizer struct {
	root *ListAllUsersParams
}

func (b ListAllUsersParams_Builder_Limit) Limit(arg *int) ListAllUsersParams_Builder_GobFinalizer {
	b.root.Limit = arg
	return ListAllUsersParams_Builder_GobFinalizer{root: b.root}
}

func (b ListAllUsersParams_Builder_GobFinalizer) Build() *ListAllUsersParams {
	return b.root
}

func NewListUsersByTenantParamsBuilder() ListUsersByTenantParams_Builder_Page {
	return ListUsersByTenantParams_Builder_Page{root: &ListUsersByTenantParams{}}
}

type ListUsersByTenantParams_Builder_Page struct {
	root *ListUsersByTenantParams
}

type ListUsersByTenantParams_Builder_Limit struct {
	root *ListUsersByTenantParams
}

func (b ListUsersByTenantParams_Builder_Page) Page(arg *int) ListUsersByTenantParams_Builder_Limit {
	b.root.Page = arg
	return ListUsersByTenantParams_Builder_Limit{root: b.root}
}

type ListUsersByTenantParams_Builder_GobFinalizer struct {
	root *ListUsersByTenantParams
}

func (b ListUsersByTenantParams_Builder_Limit) Limit(arg *int) ListUsersByTenantParams_Builder_GobFinalizer {
	b.root.Limit = arg
	return ListUsersByTenantParams_Builder_GobFinalizer{root: b.root}
}

func (b ListUsersByTenantParams_Builder_GobFinalizer) Build() *ListUsersByTenantParams {
	return b.root
}
