// Code generated by gobetter; DO NOT EDIT.

package swagger

import (
	"github.com/go-openapi/strfmt"
)

func NewUserProfileBuilder() UserProfile_Builder_BirthDate {
	return UserProfile_Builder_BirthDate{root: &UserProfile{}}
}

type UserProfile_Builder_BirthDate struct {
	root *UserProfile
}

type UserProfile_Builder_CreatedAt struct {
	root *UserProfile
}

func (b UserProfile_Builder_BirthDate) BirthDate(arg *strfmt.Date) UserProfile_Builder_CreatedAt {
	b.root.BirthDate = arg
	return UserProfile_Builder_CreatedAt{root: b.root}
}

type UserProfile_Builder_Gender struct {
	root *UserProfile
}

func (b UserProfile_Builder_CreatedAt) CreatedAt(arg strfmt.DateTime) UserProfile_Builder_Gender {
	b.root.CreatedAt = arg
	return UserProfile_Builder_Gender{root: b.root}
}

type UserProfile_Builder_Height struct {
	root *UserProfile
}

func (b UserProfile_Builder_Gender) Gender(arg *string) UserProfile_Builder_Height {
	b.root.Gender = arg
	return UserProfile_Builder_Height{root: b.root}
}

type UserProfile_Builder_ID struct {
	root *UserProfile
}

func (b UserProfile_Builder_Height) Height(arg *int64) UserProfile_Builder_ID {
	b.root.Height = arg
	return UserProfile_Builder_ID{root: b.root}
}

type UserProfile_Builder_IsMetric struct {
	root *UserProfile
}

func (b UserProfile_Builder_ID) ID(arg int64) UserProfile_Builder_IsMetric {
	b.root.ID = arg
	return UserProfile_Builder_IsMetric{root: b.root}
}

type UserProfile_Builder_UpdatedAt struct {
	root *UserProfile
}

func (b UserProfile_Builder_IsMetric) IsMetric(arg bool) UserProfile_Builder_UpdatedAt {
	b.root.IsMetric = arg
	return UserProfile_Builder_UpdatedAt{root: b.root}
}

type UserProfile_Builder_UserID struct {
	root *UserProfile
}

func (b UserProfile_Builder_UpdatedAt) UpdatedAt(arg strfmt.DateTime) UserProfile_Builder_UserID {
	b.root.UpdatedAt = arg
	return UserProfile_Builder_UserID{root: b.root}
}

type UserProfile_Builder_Weight struct {
	root *UserProfile
}

func (b UserProfile_Builder_UserID) UserID(arg string) UserProfile_Builder_Weight {
	b.root.UserID = arg
	return UserProfile_Builder_Weight{root: b.root}
}

type UserProfile_Builder_GobFinalizer struct {
	root *UserProfile
}

func (b UserProfile_Builder_Weight) Weight(arg *int64) UserProfile_Builder_GobFinalizer {
	b.root.Weight = arg
	return UserProfile_Builder_GobFinalizer{root: b.root}
}

func (b UserProfile_Builder_GobFinalizer) Build() *UserProfile {
	return b.root
}
