// Code generated by gobetter; DO NOT EDIT.

package swagger

import (
	"github.com/go-openapi/strfmt"
)

func NewUserProfileUpdateRequestBuilder() UserProfileUpdateRequest_Builder_BirthDate {
	return UserProfileUpdateRequest_Builder_BirthDate{root: &UserProfileUpdateRequest{}}
}

type UserProfileUpdateRequest_Builder_BirthDate struct {
	root *UserProfileUpdateRequest
}

type UserProfileUpdateRequest_Builder_Gender struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_BirthDate) BirthDate(arg *strfmt.Date) UserProfileUpdateRequest_Builder_Gender {
	b.root.BirthDate = arg
	return UserProfileUpdateRequest_Builder_Gender{root: b.root}
}

type UserProfileUpdateRequest_Builder_Height struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_Gender) Gender(arg *string) UserProfileUpdateRequest_Builder_Height {
	b.root.Gender = arg
	return UserProfileUpdateRequest_Builder_Height{root: b.root}
}

type UserProfileUpdateRequest_Builder_IsMetric struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_Height) Height(arg *int64) UserProfileUpdateRequest_Builder_IsMetric {
	b.root.Height = arg
	return UserProfileUpdateRequest_Builder_IsMetric{root: b.root}
}

type UserProfileUpdateRequest_Builder_Weight struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_IsMetric) IsMetric(arg *bool) UserProfileUpdateRequest_Builder_Weight {
	b.root.IsMetric = arg
	return UserProfileUpdateRequest_Builder_Weight{root: b.root}
}

type UserProfileUpdateRequest_Builder_GobFinalizer struct {
	root *UserProfileUpdateRequest
}

func (b UserProfileUpdateRequest_Builder_Weight) Weight(arg *int64) UserProfileUpdateRequest_Builder_GobFinalizer {
	b.root.Weight = arg
	return UserProfileUpdateRequest_Builder_GobFinalizer{root: b.root}
}

func (b UserProfileUpdateRequest_Builder_GobFinalizer) Build() *UserProfileUpdateRequest {
	return b.root
}
