// Code generated by gobetter; DO NOT EDIT.

package swagger

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

func NewAssignUserRoleRequestBuilder() AssignUserRoleRequest_Builder_RoleName {
	return AssignUserRoleRequest_Builder_RoleName{root: &AssignUserRoleRequest{}}
}

type AssignUserRoleRequest_Builder_RoleName struct {
	root *AssignUserRoleRequest
}

type AssignUserRoleRequest_Builder_GobFinalizer struct {
	root *AssignUserRoleRequest
}

func (b AssignUserRoleRequest_Builder_RoleName) RoleName(arg AssignUserRoleRequestRoleName) AssignUserRoleRequest_Builder_GobFinalizer {
	b.root.RoleName = arg
	return AssignUserRoleRequest_Builder_GobFinalizer{root: b.root}
}

func (b AssignUserRoleRequest_Builder_GobFinalizer) Build() *AssignUserRoleRequest {
	return b.root
}

func NewAuthUserResponseBuilder() AuthUserResponse_Builder_CreatedAt {
	return AuthUserResponse_Builder_CreatedAt{root: &AuthUserResponse{}}
}

type AuthUserResponse_Builder_CreatedAt struct {
	root *AuthUserResponse
}

type AuthUserResponse_Builder_Email struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_CreatedAt) CreatedAt(arg time.Time) AuthUserResponse_Builder_Email {
	b.root.CreatedAt = arg
	return AuthUserResponse_Builder_Email{root: b.root}
}

type AuthUserResponse_Builder_FirstName struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_Email) Email(arg openapi_types.Email) AuthUserResponse_Builder_FirstName {
	b.root.Email = arg
	return AuthUserResponse_Builder_FirstName{root: b.root}
}

type AuthUserResponse_Builder_Id struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_FirstName) FirstName(arg string) AuthUserResponse_Builder_Id {
	b.root.FirstName = arg
	return AuthUserResponse_Builder_Id{root: b.root}
}

type AuthUserResponse_Builder_LastName struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_Id) Id(arg string) AuthUserResponse_Builder_LastName {
	b.root.Id = arg
	return AuthUserResponse_Builder_LastName{root: b.root}
}

type AuthUserResponse_Builder_TenantId struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_LastName) LastName(arg string) AuthUserResponse_Builder_TenantId {
	b.root.LastName = arg
	return AuthUserResponse_Builder_TenantId{root: b.root}
}

type AuthUserResponse_Builder_UpdatedAt struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_TenantId) TenantId(arg string) AuthUserResponse_Builder_UpdatedAt {
	b.root.TenantId = arg
	return AuthUserResponse_Builder_UpdatedAt{root: b.root}
}

type AuthUserResponse_Builder_GobFinalizer struct {
	root *AuthUserResponse
}

func (b AuthUserResponse_Builder_UpdatedAt) UpdatedAt(arg time.Time) AuthUserResponse_Builder_GobFinalizer {
	b.root.UpdatedAt = arg
	return AuthUserResponse_Builder_GobFinalizer{root: b.root}
}

func (b AuthUserResponse_Builder_GobFinalizer) Build() *AuthUserResponse {
	return b.root
}

func NewAuthUsersResponseBuilder() AuthUsersResponse_Builder_Items {
	return AuthUsersResponse_Builder_Items{root: &AuthUsersResponse{}}
}

type AuthUsersResponse_Builder_Items struct {
	root *AuthUsersResponse
}

type AuthUsersResponse_Builder_Pagination struct {
	root *AuthUsersResponse
}

func (b AuthUsersResponse_Builder_Items) Items(arg []AuthUserResponse) AuthUsersResponse_Builder_Pagination {
	b.root.Items = arg
	return AuthUsersResponse_Builder_Pagination{root: b.root}
}

type AuthUsersResponse_Builder_GobFinalizer struct {
	root *AuthUsersResponse
}

func (b AuthUsersResponse_Builder_Pagination) Pagination(arg PaginationInfo) AuthUsersResponse_Builder_GobFinalizer {
	b.root.Pagination = arg
	return AuthUsersResponse_Builder_GobFinalizer{root: b.root}
}

func (b AuthUsersResponse_Builder_GobFinalizer) Build() *AuthUsersResponse {
	return b.root
}

func NewUpdateAuthUserRequestBuilder() UpdateAuthUserRequest_Builder_FirstName {
	return UpdateAuthUserRequest_Builder_FirstName{root: &UpdateAuthUserRequest{}}
}

type UpdateAuthUserRequest_Builder_FirstName struct {
	root *UpdateAuthUserRequest
}

type UpdateAuthUserRequest_Builder_LastName struct {
	root *UpdateAuthUserRequest
}

func (b UpdateAuthUserRequest_Builder_FirstName) FirstName(arg string) UpdateAuthUserRequest_Builder_LastName {
	b.root.FirstName = arg
	return UpdateAuthUserRequest_Builder_LastName{root: b.root}
}

type UpdateAuthUserRequest_Builder_GobFinalizer struct {
	root *UpdateAuthUserRequest
}

func (b UpdateAuthUserRequest_Builder_LastName) LastName(arg string) UpdateAuthUserRequest_Builder_GobFinalizer {
	b.root.LastName = arg
	return UpdateAuthUserRequest_Builder_GobFinalizer{root: b.root}
}

func (b UpdateAuthUserRequest_Builder_GobFinalizer) Build() *UpdateAuthUserRequest {
	return b.root
}

func NewUpdateUserProfileRequestBuilder() UpdateUserProfileRequest_Builder_BirthDate {
	return UpdateUserProfileRequest_Builder_BirthDate{root: &UpdateUserProfileRequest{}}
}

type UpdateUserProfileRequest_Builder_BirthDate struct {
	root *UpdateUserProfileRequest
}

type UpdateUserProfileRequest_Builder_Gender struct {
	root *UpdateUserProfileRequest
}

func (b UpdateUserProfileRequest_Builder_BirthDate) BirthDate(arg *openapi_types.Date) UpdateUserProfileRequest_Builder_Gender {
	b.root.BirthDate = arg
	return UpdateUserProfileRequest_Builder_Gender{root: b.root}
}

type UpdateUserProfileRequest_Builder_Height struct {
	root *UpdateUserProfileRequest
}

func (b UpdateUserProfileRequest_Builder_Gender) Gender(arg *UserProfileGender) UpdateUserProfileRequest_Builder_Height {
	b.root.Gender = arg
	return UpdateUserProfileRequest_Builder_Height{root: b.root}
}

type UpdateUserProfileRequest_Builder_IsMetric struct {
	root *UpdateUserProfileRequest
}

func (b UpdateUserProfileRequest_Builder_Height) Height(arg *int) UpdateUserProfileRequest_Builder_IsMetric {
	b.root.Height = arg
	return UpdateUserProfileRequest_Builder_IsMetric{root: b.root}
}

type UpdateUserProfileRequest_Builder_Weight struct {
	root *UpdateUserProfileRequest
}

func (b UpdateUserProfileRequest_Builder_IsMetric) IsMetric(arg *bool) UpdateUserProfileRequest_Builder_Weight {
	b.root.IsMetric = arg
	return UpdateUserProfileRequest_Builder_Weight{root: b.root}
}

type UpdateUserProfileRequest_Builder_GobFinalizer struct {
	root *UpdateUserProfileRequest
}

func (b UpdateUserProfileRequest_Builder_Weight) Weight(arg *int) UpdateUserProfileRequest_Builder_GobFinalizer {
	b.root.Weight = arg
	return UpdateUserProfileRequest_Builder_GobFinalizer{root: b.root}
}

func (b UpdateUserProfileRequest_Builder_GobFinalizer) Build() *UpdateUserProfileRequest {
	return b.root
}

func NewUserProfileResponseBuilder() UserProfileResponse_Builder_BirthDate {
	return UserProfileResponse_Builder_BirthDate{root: &UserProfileResponse{}}
}

type UserProfileResponse_Builder_BirthDate struct {
	root *UserProfileResponse
}

type UserProfileResponse_Builder_CreatedAt struct {
	root *UserProfileResponse
}

func (b UserProfileResponse_Builder_BirthDate) BirthDate(arg *openapi_types.Date) UserProfileResponse_Builder_CreatedAt {
	b.root.BirthDate = arg
	return UserProfileResponse_Builder_CreatedAt{root: b.root}
}

type UserProfileResponse_Builder_Gender struct {
	root *UserProfileResponse
}

func (b UserProfileResponse_Builder_CreatedAt) CreatedAt(arg time.Time) UserProfileResponse_Builder_Gender {
	b.root.CreatedAt = arg
	return UserProfileResponse_Builder_Gender{root: b.root}
}

type UserProfileResponse_Builder_Height struct {
	root *UserProfileResponse
}

func (b UserProfileResponse_Builder_Gender) Gender(arg *UserProfileGender) UserProfileResponse_Builder_Height {
	b.root.Gender = arg
	return UserProfileResponse_Builder_Height{root: b.root}
}

type UserProfileResponse_Builder_IsMetric struct {
	root *UserProfileResponse
}

func (b UserProfileResponse_Builder_Height) Height(arg *int) UserProfileResponse_Builder_IsMetric {
	b.root.Height = arg
	return UserProfileResponse_Builder_IsMetric{root: b.root}
}

type UserProfileResponse_Builder_UpdatedAt struct {
	root *UserProfileResponse
}

func (b UserProfileResponse_Builder_IsMetric) IsMetric(arg bool) UserProfileResponse_Builder_UpdatedAt {
	b.root.IsMetric = arg
	return UserProfileResponse_Builder_UpdatedAt{root: b.root}
}

type UserProfileResponse_Builder_UserId struct {
	root *UserProfileResponse
}

func (b UserProfileResponse_Builder_UpdatedAt) UpdatedAt(arg time.Time) UserProfileResponse_Builder_UserId {
	b.root.UpdatedAt = arg
	return UserProfileResponse_Builder_UserId{root: b.root}
}

type UserProfileResponse_Builder_Weight struct {
	root *UserProfileResponse
}

func (b UserProfileResponse_Builder_UserId) UserId(arg string) UserProfileResponse_Builder_Weight {
	b.root.UserId = arg
	return UserProfileResponse_Builder_Weight{root: b.root}
}

type UserProfileResponse_Builder_GobFinalizer struct {
	root *UserProfileResponse
}

func (b UserProfileResponse_Builder_Weight) Weight(arg *int) UserProfileResponse_Builder_GobFinalizer {
	b.root.Weight = arg
	return UserProfileResponse_Builder_GobFinalizer{root: b.root}
}

func (b UserProfileResponse_Builder_GobFinalizer) Build() *UserProfileResponse {
	return b.root
}

func NewUserRolesResponseBuilder() UserRolesResponse_Builder_Roles {
	return UserRolesResponse_Builder_Roles{root: &UserRolesResponse{}}
}

type UserRolesResponse_Builder_Roles struct {
	root *UserRolesResponse
}

type UserRolesResponse_Builder_UserId struct {
	root *UserRolesResponse
}

func (b UserRolesResponse_Builder_Roles) Roles(arg []string) UserRolesResponse_Builder_UserId {
	b.root.Roles = arg
	return UserRolesResponse_Builder_UserId{root: b.root}
}

type UserRolesResponse_Builder_GobFinalizer struct {
	root *UserRolesResponse
}

func (b UserRolesResponse_Builder_UserId) UserId(arg string) UserRolesResponse_Builder_GobFinalizer {
	b.root.UserId = arg
	return UserRolesResponse_Builder_GobFinalizer{root: b.root}
}

func (b UserRolesResponse_Builder_GobFinalizer) Build() *UserRolesResponse {
	return b.root
}

func NewListAllUsersParamsBuilder() ListAllUsersParams_Builder_Page {
	return ListAllUsersParams_Builder_Page{root: &ListAllUsersParams{}}
}

type ListAllUsersParams_Builder_Page struct {
	root *ListAllUsersParams
}

type ListAllUsersParams_Builder_Limit struct {
	root *ListAllUsersParams
}

func (b ListAllUsersParams_Builder_Page) Page(arg *int) ListAllUsersParams_Builder_Limit {
	b.root.Page = arg
	return ListAllUsersParams_Builder_Limit{root: b.root}
}

type ListAllUsersParams_Builder_GobFinalizer struct {
	root *ListAllUsersParams
}

func (b ListAllUsersParams_Builder_Limit) Limit(arg *int) ListAllUsersParams_Builder_GobFinalizer {
	b.root.Limit = arg
	return ListAllUsersParams_Builder_GobFinalizer{root: b.root}
}

func (b ListAllUsersParams_Builder_GobFinalizer) Build() *ListAllUsersParams {
	return b.root
}

func NewListUsersByTenantParamsBuilder() ListUsersByTenantParams_Builder_Page {
	return ListUsersByTenantParams_Builder_Page{root: &ListUsersByTenantParams{}}
}

type ListUsersByTenantParams_Builder_Page struct {
	root *ListUsersByTenantParams
}

type ListUsersByTenantParams_Builder_Limit struct {
	root *ListUsersByTenantParams
}

func (b ListUsersByTenantParams_Builder_Page) Page(arg *int) ListUsersByTenantParams_Builder_Limit {
	b.root.Page = arg
	return ListUsersByTenantParams_Builder_Limit{root: b.root}
}

type ListUsersByTenantParams_Builder_GobFinalizer struct {
	root *ListUsersByTenantParams
}

func (b ListUsersByTenantParams_Builder_Limit) Limit(arg *int) ListUsersByTenantParams_Builder_GobFinalizer {
	b.root.Limit = arg
	return ListUsersByTenantParams_Builder_GobFinalizer{root: b.root}
}

func (b ListUsersByTenantParams_Builder_GobFinalizer) Build() *ListUsersByTenantParams {
	return b.root
}
