database:
  host: some-db-host
  name: iamservice
  user: neondb_owner
  sslmode: require
  parameters:
    channel_binding: require
server:
  domain: https://iamservice.some-hosting.dev
gcloud:
  email:
    user: toly@pluralfusion.com
    from: noreply@pluralfusion.com
