// Code generated by gobetter; DO NOT EDIT.

package repo

import (
	"time"
)

func NewAuthUserEntityBuilder() AuthUserEntity_Builder_ID {
	return AuthUserEntity_Builder_ID{root: &AuthUserEntity{}}
}

type AuthUserEntity_Builder_ID struct {
	root *AuthUserEntity
}

type AuthUserEntity_Builder_Email struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_ID) ID(arg string) AuthUserEntity_Builder_Email {
	b.root.ID = arg
	return AuthUserEntity_Builder_Email{root: b.root}
}

type AuthUserEntity_Builder_PasswordHash struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_Email) Email(arg string) AuthUserEntity_Builder_PasswordHash {
	b.root.Email = arg
	return AuthUserEntity_Builder_PasswordHash{root: b.root}
}

type AuthUserEntity_Builder_FirstName struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_PasswordHash) PasswordHash(arg string) AuthUserEntity_Builder_FirstName {
	b.root.PasswordHash = arg
	return AuthUserEntity_Builder_FirstName{root: b.root}
}

type AuthUserEntity_Builder_LastName struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_FirstName) FirstName(arg string) AuthUserEntity_Builder_LastName {
	b.root.FirstName = arg
	return AuthUserEntity_Builder_LastName{root: b.root}
}

type AuthUserEntity_Builder_TenantID struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_LastName) LastName(arg string) AuthUserEntity_Builder_TenantID {
	b.root.LastName = arg
	return AuthUserEntity_Builder_TenantID{root: b.root}
}

type AuthUserEntity_Builder_IsActive struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_TenantID) TenantID(arg string) AuthUserEntity_Builder_IsActive {
	b.root.TenantID = arg
	return AuthUserEntity_Builder_IsActive{root: b.root}
}

type AuthUserEntity_Builder_EmailVerified struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_IsActive) IsActive(arg bool) AuthUserEntity_Builder_EmailVerified {
	b.root.IsActive = arg
	return AuthUserEntity_Builder_EmailVerified{root: b.root}
}

type AuthUserEntity_Builder_CreatedAt struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_EmailVerified) EmailVerified(arg bool) AuthUserEntity_Builder_CreatedAt {
	b.root.EmailVerified = arg
	return AuthUserEntity_Builder_CreatedAt{root: b.root}
}

type AuthUserEntity_Builder_UpdatedAt struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_CreatedAt) CreatedAt(arg time.Time) AuthUserEntity_Builder_UpdatedAt {
	b.root.CreatedAt = arg
	return AuthUserEntity_Builder_UpdatedAt{root: b.root}
}

type AuthUserEntity_Builder_GobFinalizer struct {
	root *AuthUserEntity
}

func (b AuthUserEntity_Builder_UpdatedAt) UpdatedAt(arg time.Time) AuthUserEntity_Builder_GobFinalizer {
	b.root.UpdatedAt = arg
	return AuthUserEntity_Builder_GobFinalizer{root: b.root}
}

func (b AuthUserEntity_Builder_GobFinalizer) Build() *AuthUserEntity {
	return b.root
}

func NewAuthRoleEntityBuilder() AuthRoleEntity_Builder_ID {
	return AuthRoleEntity_Builder_ID{root: &AuthRoleEntity{}}
}

type AuthRoleEntity_Builder_ID struct {
	root *AuthRoleEntity
}

type AuthRoleEntity_Builder_Name struct {
	root *AuthRoleEntity
}

func (b AuthRoleEntity_Builder_ID) ID(arg *int) AuthRoleEntity_Builder_Name {
	b.root.ID = arg
	return AuthRoleEntity_Builder_Name{root: b.root}
}

type AuthRoleEntity_Builder_Description struct {
	root *AuthRoleEntity
}

func (b AuthRoleEntity_Builder_Name) Name(arg string) AuthRoleEntity_Builder_Description {
	b.root.Name = arg
	return AuthRoleEntity_Builder_Description{root: b.root}
}

type AuthRoleEntity_Builder_GobFinalizer struct {
	root *AuthRoleEntity
}

func (b AuthRoleEntity_Builder_Description) Description(arg *string) AuthRoleEntity_Builder_GobFinalizer {
	b.root.Description = arg
	return AuthRoleEntity_Builder_GobFinalizer{root: b.root}
}

func (b AuthRoleEntity_Builder_GobFinalizer) Build() *AuthRoleEntity {
	return b.root
}

func NewAuthUserRoleEntityBuilder() AuthUserRoleEntity_Builder_UserID {
	return AuthUserRoleEntity_Builder_UserID{root: &AuthUserRoleEntity{}}
}

type AuthUserRoleEntity_Builder_UserID struct {
	root *AuthUserRoleEntity
}

type AuthUserRoleEntity_Builder_RoleID struct {
	root *AuthUserRoleEntity
}

func (b AuthUserRoleEntity_Builder_UserID) UserID(arg string) AuthUserRoleEntity_Builder_RoleID {
	b.root.UserID = arg
	return AuthUserRoleEntity_Builder_RoleID{root: b.root}
}

type AuthUserRoleEntity_Builder_GobFinalizer struct {
	root *AuthUserRoleEntity
}

func (b AuthUserRoleEntity_Builder_RoleID) RoleID(arg int) AuthUserRoleEntity_Builder_GobFinalizer {
	b.root.RoleID = arg
	return AuthUserRoleEntity_Builder_GobFinalizer{root: b.root}
}

func (b AuthUserRoleEntity_Builder_GobFinalizer) Build() *AuthUserRoleEntity {
	return b.root
}

func NewTenantEntityBuilder() TenantEntity_Builder_ID {
	return TenantEntity_Builder_ID{root: &TenantEntity{}}
}

type TenantEntity_Builder_ID struct {
	root *TenantEntity
}

type TenantEntity_Builder_Name struct {
	root *TenantEntity
}

func (b TenantEntity_Builder_ID) ID(arg string) TenantEntity_Builder_Name {
	b.root.ID = arg
	return TenantEntity_Builder_Name{root: b.root}
}

type TenantEntity_Builder_Description struct {
	root *TenantEntity
}

func (b TenantEntity_Builder_Name) Name(arg string) TenantEntity_Builder_Description {
	b.root.Name = arg
	return TenantEntity_Builder_Description{root: b.root}
}

type TenantEntity_Builder_CreatedAt struct {
	root *TenantEntity
}

func (b TenantEntity_Builder_Description) Description(arg string) TenantEntity_Builder_CreatedAt {
	b.root.Description = arg
	return TenantEntity_Builder_CreatedAt{root: b.root}
}

type TenantEntity_Builder_UpdatedAt struct {
	root *TenantEntity
}

func (b TenantEntity_Builder_CreatedAt) CreatedAt(arg time.Time) TenantEntity_Builder_UpdatedAt {
	b.root.CreatedAt = arg
	return TenantEntity_Builder_UpdatedAt{root: b.root}
}

type TenantEntity_Builder_GobFinalizer struct {
	root *TenantEntity
}

func (b TenantEntity_Builder_UpdatedAt) UpdatedAt(arg time.Time) TenantEntity_Builder_GobFinalizer {
	b.root.UpdatedAt = arg
	return TenantEntity_Builder_GobFinalizer{root: b.root}
}

func (b TenantEntity_Builder_GobFinalizer) Build() *TenantEntity {
	return b.root
}

func NewRefreshTokenEntityBuilder() RefreshTokenEntity_Builder_ID {
	return RefreshTokenEntity_Builder_ID{root: &RefreshTokenEntity{}}
}

type RefreshTokenEntity_Builder_ID struct {
	root *RefreshTokenEntity
}

type RefreshTokenEntity_Builder_UserID struct {
	root *RefreshTokenEntity
}

func (b RefreshTokenEntity_Builder_ID) ID(arg string) RefreshTokenEntity_Builder_UserID {
	b.root.ID = arg
	return RefreshTokenEntity_Builder_UserID{root: b.root}
}

type RefreshTokenEntity_Builder_TokenHash struct {
	root *RefreshTokenEntity
}

func (b RefreshTokenEntity_Builder_UserID) UserID(arg string) RefreshTokenEntity_Builder_TokenHash {
	b.root.UserID = arg
	return RefreshTokenEntity_Builder_TokenHash{root: b.root}
}

type RefreshTokenEntity_Builder_IssuedAt struct {
	root *RefreshTokenEntity
}

func (b RefreshTokenEntity_Builder_TokenHash) TokenHash(arg string) RefreshTokenEntity_Builder_IssuedAt {
	b.root.TokenHash = arg
	return RefreshTokenEntity_Builder_IssuedAt{root: b.root}
}

type RefreshTokenEntity_Builder_ExpiresAt struct {
	root *RefreshTokenEntity
}

func (b RefreshTokenEntity_Builder_IssuedAt) IssuedAt(arg time.Time) RefreshTokenEntity_Builder_ExpiresAt {
	b.root.IssuedAt = arg
	return RefreshTokenEntity_Builder_ExpiresAt{root: b.root}
}

type RefreshTokenEntity_Builder_Revoked struct {
	root *RefreshTokenEntity
}

func (b RefreshTokenEntity_Builder_ExpiresAt) ExpiresAt(arg time.Time) RefreshTokenEntity_Builder_Revoked {
	b.root.ExpiresAt = arg
	return RefreshTokenEntity_Builder_Revoked{root: b.root}
}

type RefreshTokenEntity_Builder_GobFinalizer struct {
	root *RefreshTokenEntity
}

func (b RefreshTokenEntity_Builder_Revoked) Revoked(arg bool) RefreshTokenEntity_Builder_GobFinalizer {
	b.root.Revoked = arg
	return RefreshTokenEntity_Builder_GobFinalizer{root: b.root}
}

func (b RefreshTokenEntity_Builder_GobFinalizer) Build() *RefreshTokenEntity {
	return b.root
}

func NewUserProfileEntityBuilder() UserProfileEntity_Builder_ID {
	return UserProfileEntity_Builder_ID{root: &UserProfileEntity{}}
}

type UserProfileEntity_Builder_ID struct {
	root *UserProfileEntity
}

type UserProfileEntity_Builder_UserID struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_ID) ID(arg *int) UserProfileEntity_Builder_UserID {
	b.root.ID = arg
	return UserProfileEntity_Builder_UserID{root: b.root}
}

type UserProfileEntity_Builder_Height struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_UserID) UserID(arg string) UserProfileEntity_Builder_Height {
	b.root.UserID = arg
	return UserProfileEntity_Builder_Height{root: b.root}
}

type UserProfileEntity_Builder_Weight struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_Height) Height(arg *int) UserProfileEntity_Builder_Weight {
	b.root.Height = arg
	return UserProfileEntity_Builder_Weight{root: b.root}
}

type UserProfileEntity_Builder_Gender struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_Weight) Weight(arg *int) UserProfileEntity_Builder_Gender {
	b.root.Weight = arg
	return UserProfileEntity_Builder_Gender{root: b.root}
}

type UserProfileEntity_Builder_BirthDate struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_Gender) Gender(arg *string) UserProfileEntity_Builder_BirthDate {
	b.root.Gender = arg
	return UserProfileEntity_Builder_BirthDate{root: b.root}
}

type UserProfileEntity_Builder_IsMetric struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_BirthDate) BirthDate(arg *time.Time) UserProfileEntity_Builder_IsMetric {
	b.root.BirthDate = arg
	return UserProfileEntity_Builder_IsMetric{root: b.root}
}

type UserProfileEntity_Builder_CreatedAt struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_IsMetric) IsMetric(arg bool) UserProfileEntity_Builder_CreatedAt {
	b.root.IsMetric = arg
	return UserProfileEntity_Builder_CreatedAt{root: b.root}
}

type UserProfileEntity_Builder_UpdatedAt struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_CreatedAt) CreatedAt(arg time.Time) UserProfileEntity_Builder_UpdatedAt {
	b.root.CreatedAt = arg
	return UserProfileEntity_Builder_UpdatedAt{root: b.root}
}

type UserProfileEntity_Builder_GobFinalizer struct {
	root *UserProfileEntity
}

func (b UserProfileEntity_Builder_UpdatedAt) UpdatedAt(arg time.Time) UserProfileEntity_Builder_GobFinalizer {
	b.root.UpdatedAt = arg
	return UserProfileEntity_Builder_GobFinalizer{root: b.root}
}

func (b UserProfileEntity_Builder_GobFinalizer) Build() *UserProfileEntity {
	return b.root
}
