// Code generated by gobetter; DO NOT EDIT.

package outport

func NewMailContentBuilder() MailContent_Builder_ContentType {
	return MailContent_Builder_ContentType{root: &MailContent{}}
}

type MailContent_Builder_ContentType struct {
	root *MailContent
}

type MailContent_Builder_Title struct {
	root *MailContent
}

func (b MailContent_Builder_ContentType) ContentType(arg string) MailContent_Builder_Title {
	b.root.ContentType = arg
	return MailContent_Builder_Title{root: b.root}
}

type MailContent_Builder_Body struct {
	root *MailContent
}

func (b MailContent_Builder_Title) Title(arg string) MailContent_Builder_Body {
	b.root.Title = arg
	return MailContent_Builder_Body{root: b.root}
}

type MailContent_Builder_GobFinalizer struct {
	root *MailContent
}

func (b MailContent_Builder_Body) Body(arg string) MailContent_Builder_GobFinalizer {
	b.root.Body = arg
	return MailContent_Builder_GobFinalizer{root: b.root}
}

func (b MailContent_Builder_GobFinalizer) Build() *MailContent {
	return b.root
}
