// Code generated by gobetter; DO NOT EDIT.

package outport

func NewPortsBuilder() Ports_Builder_AuthUserPersist {
	return Ports_Builder_AuthUserPersist{root: &Ports{}}
}

type Ports_Builder_AuthUserPersist struct {
	root *Ports
}

type Ports_Builder_UserProfilePersist struct {
	root *Ports
}

func (b Ports_Builder_AuthUserPersist) AuthUserPersist(arg AuthUserPersist) Ports_Builder_UserProfilePersist {
	b.root.AuthUserPersist = arg
	return Ports_Builder_UserProfilePersist{root: b.root}
}

type Ports_Builder_Tx struct {
	root *Ports
}

func (b Ports_Builder_UserProfilePersist) UserProfilePersist(arg UserProfilePersist) Ports_Builder_Tx {
	b.root.UserProfilePersist = arg
	return Ports_Builder_Tx{root: b.root}
}

type Ports_Builder_Mailer struct {
	root *Ports
}

func (b Ports_Builder_Tx) Tx(arg TxPort) Ports_Builder_Mailer {
	b.root.Tx = arg
	return Ports_Builder_Mailer{root: b.root}
}

type Ports_Builder_GobFinalizer struct {
	root *Ports
}

func (b Ports_Builder_Mailer) Mailer(arg Mailer) Ports_Builder_GobFinalizer {
	b.root.Mailer = arg
	return Ports_Builder_GobFinalizer{root: b.root}
}

func (b Ports_Builder_GobFinalizer) Build() *Ports {
	return b.root
}
