// Code generated by gobetter; DO NOT EDIT.

package repo

func NewContactEntityBuilder() ContactEntity_Builder_ID {
	return ContactEntity_Builder_ID{root: &ContactEntity{}}
}

type ContactEntity_Builder_ID struct {
	root *ContactEntity
}

type ContactEntity_Builder_FirstName struct {
	root *ContactEntity
}

func (b ContactEntity_Builder_ID) ID(arg *int64) ContactEntity_Builder_FirstName {
	b.root.ID = arg
	return ContactEntity_Builder_FirstName{root: b.root}
}

type ContactEntity_Builder_LastName struct {
	root *ContactEntity
}

func (b ContactEntity_Builder_FirstName) FirstName(arg string) ContactEntity_Builder_LastName {
	b.root.FirstName = arg
	return ContactEntity_Builder_LastName{root: b.root}
}

type ContactEntity_Builder_GobFinalizer struct {
	root *ContactEntity
}

func (b ContactEntity_Builder_LastName) LastName(arg string) ContactEntity_Builder_GobFinalizer {
	b.root.LastName = arg
	return ContactEntity_Builder_GobFinalizer{root: b.root}
}

func (b ContactEntity_Builder_GobFinalizer) Build() *ContactEntity {
	return b.root
}
