// Code generated by gobetter; DO NOT EDIT.

package model

func NewAddContactBuilder() AddContact_Builder_FirstName {
	return AddContact_Builder_FirstName{root: &AddContact{}}
}

type AddContact_Builder_FirstName struct {
	root *AddContact
}

type AddContact_Builder_LastName struct {
	root *AddContact
}

func (b AddContact_Builder_FirstName) FirstName(arg *string) AddContact_Builder_LastName {
	b.root.FirstName = arg
	return AddContact_Builder_LastName{root: b.root}
}

type AddContact_Builder_GobFinalizer struct {
	root *AddContact
}

func (b AddContact_Builder_LastName) LastName(arg *string) AddContact_Builder_GobFinalizer {
	b.root.LastName = arg
	return AddContact_Builder_GobFinalizer{root: b.root}
}

func (b AddContact_Builder_GobFinalizer) Build() *AddContact {
	return b.root
}
