// Code generated by gobetter; DO NOT EDIT.

package model

func NewContactBuilder() Contact_Builder_ID {
	return Contact_Builder_ID{root: &Contact{}}
}

type Contact_Builder_ID struct {
	root *Contact
}

type Contact_Builder_FirstName struct {
	root *Contact
}

func (b Contact_Builder_ID) ID(arg *string) Contact_Builder_FirstName {
	b.root.ID = arg
	return Contact_Builder_FirstName{root: b.root}
}

type Contact_Builder_LastName struct {
	root *Contact
}

func (b Contact_Builder_FirstName) FirstName(arg *string) Contact_Builder_LastName {
	b.root.FirstName = arg
	return Contact_Builder_LastName{root: b.root}
}

type Contact_Builder_GobFinalizer struct {
	root *Contact
}

func (b Contact_Builder_LastName) LastName(arg *string) Contact_Builder_GobFinalizer {
	b.root.LastName = arg
	return Contact_Builder_GobFinalizer{root: b.root}
}

func (b Contact_Builder_GobFinalizer) Build() *Contact {
	return b.root
}
