// Code generated by gobetter; DO NOT EDIT.

package model

func NewAuthUserBuilder() AuthUser_Builder_ID {
	return AuthUser_Builder_ID{root: &AuthUser{}}
}

type AuthUser_Builder_ID struct {
	root *AuthUser
}

type AuthUser_Builder_Email struct {
	root *AuthUser
}

func (b AuthUser_Builder_ID) ID(arg string) AuthUser_Builder_Email {
	b.root.ID = arg
	return AuthUser_Builder_Email{root: b.root}
}

type AuthUser_Builder_PasswordHash struct {
	root *AuthUser
}

func (b AuthUser_Builder_Email) Email(arg string) AuthUser_Builder_PasswordHash {
	b.root.Email = arg
	return AuthUser_Builder_PasswordHash{root: b.root}
}

type AuthUser_Builder_FirstName struct {
	root *AuthUser
}

func (b AuthUser_Builder_PasswordHash) PasswordHash(arg string) AuthUser_Builder_FirstName {
	b.root.PasswordHash = arg
	return AuthUser_Builder_FirstName{root: b.root}
}

type AuthUser_Builder_LastName struct {
	root *AuthUser
}

func (b AuthUser_Builder_FirstName) FirstName(arg string) AuthUser_Builder_LastName {
	b.root.FirstName = arg
	return AuthUser_Builder_LastName{root: b.root}
}

type AuthUser_Builder_IsActive struct {
	root *AuthUser
}

func (b AuthUser_Builder_LastName) LastName(arg string) AuthUser_Builder_IsActive {
	b.root.LastName = arg
	return AuthUser_Builder_IsActive{root: b.root}
}

type AuthUser_Builder_EmailVerified struct {
	root *AuthUser
}

func (b AuthUser_Builder_IsActive) IsActive(arg bool) AuthUser_Builder_EmailVerified {
	b.root.IsActive = arg
	return AuthUser_Builder_EmailVerified{root: b.root}
}

type AuthUser_Builder_CreatedAt struct {
	root *AuthUser
}

func (b AuthUser_Builder_EmailVerified) EmailVerified(arg bool) AuthUser_Builder_CreatedAt {
	b.root.EmailVerified = arg
	return AuthUser_Builder_CreatedAt{root: b.root}
}

type AuthUser_Builder_UpdatedAt struct {
	root *AuthUser
}

func (b AuthUser_Builder_CreatedAt) CreatedAt(arg string) AuthUser_Builder_UpdatedAt {
	b.root.CreatedAt = arg
	return AuthUser_Builder_UpdatedAt{root: b.root}
}

type AuthUser_Builder_GobFinalizer struct {
	root *AuthUser
}

func (b AuthUser_Builder_UpdatedAt) UpdatedAt(arg string) AuthUser_Builder_GobFinalizer {
	b.root.UpdatedAt = arg
	return AuthUser_Builder_GobFinalizer{root: b.root}
}

func (b AuthUser_Builder_GobFinalizer) Build() *AuthUser {
	return b.root
}
