swagger: '2.0'
info:
  title: Tenant Management API
  description: API for tenant management operations
  version: 1.0.0

definitions:
  PaginationInfo:
    type: object
    required:
      - page
      - limit
      - total
      - totalPages
    properties:
      page:
        type: integer
        x-nullable: false
        description: Current page number
      limit:
        type: integer
        x-nullable: false
        description: Number of items per page
      total:
        type: integer
        x-nullable: false
        description: Total number of items
      totalPages:
        type: integer
        x-nullable: false
        description: Total number of pages

paths:
  /api/v1/a:
    get:
      summary: List all tenants (Sysadmin only)
      responses:
        200:
          description: Tenants retrieved successfully

