openapi: 3.0.3
info:
  title: Common API Components
  description: Common API components and schemas
  version: 1.0.0

security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Bearer token authentication. Format: Bearer {token}'
  schemas:
    PaginationInfo:
      type: object
      required:
        - page
        - limit
        - total
        - totalPages
      properties:
        page:
          type: integer
          nullable: false
          description: Current page number
        limit:
          type: integer
          nullable: false
          description: Number of items per page
        total:
          type: integer
          nullable: false
          description: Total number of items
        totalPages:
          type: integer
          nullable: false
          description: Total number of pages

paths:
  /api/v1/version:
    get:
      summary: Get service version
      responses:
        '200':
          description: Service version
