openapi: 3.0.3
info:
  title: Tenant Management API
  description: API for tenant management operations
  version: 1.0.0

paths:
  /api/v1/tenants:
    get:
      operationId: getAllTenants
      summary: List all tenants (Sysadmin only)
      description: Returns a list of all tenants in the system. Requires sysadmin role.
      tags:
        - Tenants
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Number of tenants per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: active
          in: query
          description: Filter by active status
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Tenants retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantListResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - requires sysadmin role
        '500':
          description: Internal server error

    post:
      operationId: createTenant
      summary: Create a new tenant (Sysadmin only)
      description: Creates a new tenant in the system. Requires sysadmin role.
      tags:
        - Tenants
      requestBody:
        description: Tenant creation information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantCreateRequest'
      responses:
        '201':
          description: Tenant successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantResponse'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - requires sysadmin role
        '409':
          description: Tenant already exists (duplicate ID)
        '500':
          description: Internal server error

  /api/v1/tenants/{tenantId}:
    get:
      operationId: getTenantById
      summary: Get tenant by ID (Sysadmin only)
      description: Returns detailed information about a specific tenant. Requires sysadmin role.
      tags:
        - Tenants
      parameters:
        - name: tenantId
          in: path
          required: true
          description: The ID of the tenant to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Tenant retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - requires sysadmin role
        '404':
          description: Tenant not found
        '500':
          description: Internal server error

    put:
      operationId: updateTenantById
      summary: Update tenant (Sysadmin only)
      description: Updates an existing tenant. Requires sysadmin role.
      tags:
        - Tenants
      parameters:
        - name: tenantId
          in: path
          required: true
          description: The ID of the tenant to update
          schema:
            type: string
      requestBody:
        description: Tenant update information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantUpdateRequest'
      responses:
        '200':
          description: Tenant successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantResponse'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - requires sysadmin role
        '404':
          description: Tenant not found
        '500':
          description: Internal server error

    delete:
      operationId: deleteTenantById
      summary: Delete tenant (Sysadmin only)
      description: Deletes a tenant from the system. This will also delete all associated users. Requires sysadmin role.
      tags:
        - Tenants
      parameters:
        - name: tenantId
          in: path
          required: true
          description: The ID of the tenant to delete
          schema:
            type: string
      responses:
        '200':
          description: Tenant successfully deleted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - requires sysadmin role
        '404':
          description: Tenant not found
        '500':
          description: Internal server error

components:
  schemas:
    TenantCreateRequest:
      type: object
      description: 'Request payload for creating a new tenant'
      properties:
        id:
          type: string
          nullable: false
          example: 'acme-corp'
          description: 'Unique tenant identifier'
        name:
          type: string
          nullable: false
          example: 'Acme Corporation'
          description: 'Human-readable tenant name'
        description:
          type: string
          nullable: false
          example: 'Acme Corporation tenant for enterprise customers'
          description: 'Optional description of the tenant'
      required:
        - id
        - name
        - description

    TenantUpdateRequest:
      type: object
      description: 'Request payload for updating a tenant'
      properties:
        name:
          type: string
          nullable: false
          example: 'Acme Corporation Updated'
          description: 'Human-readable tenant name'
        description:
          type: string
          nullable: false
          example: 'Updated description for Acme Corporation'
          description: 'Optional description of the tenant'
      required:
        - name
        - description

    TenantResponse:
      type: object
      description: 'Tenant information response'
      properties:
        id:
          type: string
          nullable: false
          example: 'acme-corp'
          description: 'Unique tenant identifier'
        name:
          type: string
          nullable: false
          example: 'Acme Corporation'
          description: 'Human-readable tenant name'
        description:
          type: string
          nullable: false
          example: 'Acme Corporation tenant for enterprise customers'
          description: 'Optional description of the tenant'
        createdAt:
          type: string
          nullable: false
          format: date-time
          example: '2023-12-01T10:00:00Z'
          description: 'Tenant creation timestamp'
        updatedAt:
          type: string
          nullable: false
          format: date-time
          example: '2023-12-01T10:00:00Z'
          description: 'Last tenant update timestamp'
      required:
        - id
        - name
        - description
        - createdAt
        - updatedAt

    TenantListResponse:
      type: object
      required:
        - tenants
        - pagination
      properties:
        tenants:
          type: array
          items:
            $ref: '#/components/schemas/TenantResponse'
        pagination:
          $ref: './common.yaml#/components/schemas/PaginationInfo'
